### ISSUE TITLE
Story table: How do we handle `.there_is_another` loops?

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#220]
When asking about cases for example, these are the separate screens that may be shown:

What is docket number for the first case? `cases[0].docket_number` (A: 1234)
Do you have another case? `cases.there_is_another` (A: yes)
What is the docket number for the second case? `cases[1].docket_number` (A: 5678)
Do you have another case? `cases.there_is_another` (A: no)

In the first instance, the answer should be ‘yes’, but in the second instance, the answer should be ‘no’. It’s the same variable both times, though. Is it possible to handle that in a story table somehow?

**Comment by niharikasingh** [comment]
Looks like `there_is_another` is yet another Docassemble special feature. Could we do something like always fill `there_is_another` with `no` by default, **unless** the story table has `variable[n+1].sub_field`? 

So in this case, because the story table has `cases[0].docket_number` and `cases[1].docket_number`, we will answer `there_is_another` with `yes` the first time, and then the default `no`. 

The story table won't explicitly need to specify the values for `there_is_another` because we can just assume those based on the rest of the values in the story table.

**Comment by plocket** [comment]
That should be doable! I'd say we should also take care to ignore any `.there_is_another` variables the developers may accidentally set.

**Comment by plocket** [comment]
Note to self: check that the regex will actually work out for that because there are definitely often more than one vars with indexes. It will be a fair amount of fiddling.

**Comment by plocket** [comment]
If we add a column for the `sought var`, it will take care of this problem. See https://github.com/plocket/docassemble-cucumber/pull/221#issuecomment-843425980

**Comment by plocket** [comment]
`sought` column is what we're going with, but it's optional, so we want to think about whether we will handle this as a special case in case that value is missing or whether we will document that this is considered part of a loop, so it's required to have a `sought` value.

**Comment by plocket** [comment]
Actually, the sought var in here would always be the same. There's no way to differentiate. Maybe we'll try to detect as you describe above. Bleh. Or this may need to be a special case where the 'value' is a number that we can count down. Can't face the logic right now.

**Comment by plocket** [comment]
The bug is taken care of, but discussions are still ongoing about the best way to handle this. People are confused by the number in the `value` column. @ BryceStevenWilley had a suggestion that at least one other person (other than me) also found compelling:

Do not accept a `.there_is_another` row at all. If the developer puts one in, give them a message in a report with instructions and a link to the documentation. They will be told that everyone should use `.target_number` and then people can just put the number of items in the list as the value. Our code can (I think) handle answering `.there_is_another` type questions with that information if needed.

I think it's possible and this way devs will _have_ to look at the docs. That is, devs _need_ to look at the docs to understand the current procedure, but it's very likely that they won't. With the new proposed implementation, it'll be much easier to tell when something's gone wrong and much easier to explain what to do.

Would appreciate further thoughts.

---

Btw, I tried writing documentation to explain that `value` should be the number of times you answer 'Yes' to the `.there_is_another` question, but it was very hard to do and I think it still wasn't clear and is part of what's giving me a lot of hesitation about the current methodology:

### `.there_is_another` loop

This special row's `value` should be the number of times to answer 'Yes' to the `.there_is_another` question.

To make 3 users, you make the first user then answer 'Yes' 2 times to create the second and third user. That means the `value` in the row should be `2`:

```
      | x.there_is_another | 2 | users.there_is_another |
```

You will still need to include the rows for the information for all three `users`.

```
      | x[i].name.first | Umi | users[0].name.first |
      | x.there_is_another | 2 | users.there_is_another |
      | x[i].name.first | Ulli | users[1].name.first |
      | x[i].name.first | Ulla | users[2].name.first |
```

The order doesn't matter, it just may be more visually clear as shown above.
