### ISSUE TITLE
Make a global variable for the permitted timeout

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#31]
Not urgent, but I wonder if we should be using a global variable for the permitted timeout, and then this should just be `env_vars.TIMEOUT - 2000` or something.

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-cucumber/pull/23#r527048977_

**Comment by plocket** [comment]
This is interesting. We were recently talking about how it's annoying to deal with it in two places and I totally forgot this issue. `scope.timeout` didn't quite work because you have to set cucumber's timeout before scope becomes available. Maybe an env variable would be useful for this at least for us as test framework developers. Also see #82 (allow devs to set timeouts somewhat arbitrarily to allow for known big documents or long load times). Would we ever make it into a secret? @niharikasingh , @berit ?

Also, we should test whether the page timeout circumvents the cucumber timeout when it's shorter. Does that mean we want cucumber to always have an infinite timeout? Hmm, not sure, cucumber things can still go wrong. Unfortunately, modifying the cucumber timeout is more difficult (you have to pass it in as an argument), but it may be better to handle that on a case-by-case basis.

**Comment by niharikasingh** [comment]
I don't think timeouts need to be *secret*. They can probably be in the public `.env` file. 

The only reason to make them a secret would be if it is easier to make *everything* a secret, just for consistency's sake.

**Comment by plocket** [comment]
Something like an alkiln.config is worth thinking about. I hesitate to add another file to upkeep as we develop the package, but secrets are somewhat obstructive as an all-purpose tool for storing preferences since you can't see what's in them. Still, it would be another file to update...

**Comment by plocket** [comment]
Maybe we could have a config in this library and overwrite it with a local config if people make one. My brain isn't currently telling me how that could be done.

**Comment by plocket** [comment]
We now have a global var and a Step for custom max Step time that should work per Scenario (once it's fixed). That seems good enough for now. I think adding a config would make things more confusing.

If devs find it way too annoying to set for each Scenario, it'll be worth reconsidering.
