### ISSUE TITLE
Change base64 encoder fallback string to be more clear and descriptive

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#44]
change string to something like "will never match existing dom node"

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-cucumber/pull/33#discussion_r530051120_

**Comment by niharikasingh** [comment]
The `base64` function was outdated and removed. It has been replaced by `toBase64` which doesn't have a corresponding fallback string. I think this issue can be closed.

**Comment by plocket** [comment]
Do we want to add a fallback string for `toBase64` or do we want to handle that upstream of `toBase64`?
