### ISSUE TITLE
Reference related docassemble code in name attr base64 encoder

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#46]
pointer to docassemble code would be nice, so people know the B/R distinction exists.

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-cucumber/pull/33#discussion_r530055518_

**Comment by plocket** [comment]
Reference: https://github.com/jhpyle/docassemble/blob/595ad0a08572c0188f9ab49b1a6af99a3621cd42/docassemble_base/docassemble/base/standardformatter.py#L2108

**Comment by niharikasingh** [comment]
I don't think the `checkboxNameAttribute` function exists anymore, or the code this referred to, so this might be a moot point now.

**Comment by plocket** [comment]
There's still decryption going on when we get the guesses about a field's possible variable names. Something called through `scope.getFields()` or something. Something calculating the variable name. It references`[B'` and `[R'`.
