### ISSUE TITLE
Action: Remove need for repeating `shell: bash`

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#528]
illegitimate nitpick: it is out-of-scope of this PR, but I believe https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun will remove the need of repeating the `shell: bash`.

_Originally posted by @k3KAW8Pnf7mkmdSMPHz27 in https://github.com/SuffolkLITLab/ALKiln/pull/527#discussion_r833608381_

**Comment by BryceStevenWilley** [comment]
I'm actually convinced that the default shell in the Github Actions is bash (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell), but the things that we can't actually control is that the default in `npm run ...` is shell. Changing the npm default makes things not usable in windows locally though. Some more discussion in #540.

So, fairly certain that just removing `shell: bash` would be fine, we don't need to use the `defaults`.

**Comment by plocket** [comment]
I keep trying to remove `shell: bash` in various places, like our action.yml, and keep running into errors.

**Comment by BryceStevenWilley** [comment]
What are the errors? The [one place I can find you having to add it back](https://github.com/SuffolkLITLab/ALKiln/commit/6b741f0992276180d377242a24415a98ddff859c), there were other problems with the action.yml syntax (which you fixed in a subsequent commit, specifically using `run: |` instead of `run:`). I can't actually see what was going wrong in that commit though.

**Comment by plocket** [comment]
Good eye, so I tried it again and still got an error that shell was required:
- Commit: https://github.com/SuffolkLITLab/ALKiln/commit/264dadb2d79c97a5be811d4c6543ac5762ae9b60
- Test failure: https://github.com/plocket/docassemble-CompositeActionsTest/actions/runs/3055845896/jobs/4929362503

**Comment by BryceStevenWilley** [comment]
Hm, I see. Looking into it more, [`shell` is required when `run` is set in a step](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsshell), specifically in `action.yml` / composite actions. So I'm not sure the original change or my suggestion are possible in the `action.yml`, and we already don't specify `shell` in [our workflow file](https://github.com/SuffolkLITLab/ALKiln/blob/releases/v4/.github/workflows/test_tests.yml). Apologies, I didn't realize that workflow files and `action.yml` files have such different rules.

I suggest we close this issue.

**Comment by BryceStevenWilley** [comment]
Hm, I see. Looking into it more, [`shell` is required when `run` is set in a step](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsshell), specifically in `action.yml` / composite actions. So I'm not sure the original change or my suggestion are possible in the `action.yml`, and we already don't specify `shell` in [our workflow file](https://github.com/SuffolkLITLab/ALKiln/blob/releases/v4/.github/workflows/test_tests.yml). 

I suggest we close this issue.

**Comment by plocket** [comment]
If we've chosen to drop support for developing in Windows, we can use `default`, right? Is it worth it?

**Comment by BryceStevenWilley** [comment]
1) not sure we can use `default`? That would be invalid yaml, as composite actions specifically say that the `shell` param is required, making me think that we need to specify `bash`. If we are allowed to use `default`, give `default` does [almost exactly the same thing as bash on Ubuntu runners](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell), I don't really think it's worth the change to be more vague about which shell is running.
2) I don't think Windows support matters here, as the workflow runners will be Ubuntu by default, and I don't think most people will want to change them to Windows (if they do, they can still use a separate Ubuntu workflow for just Kiln stuff).

**Comment by plocket** [comment]
Closing because it turns out we do need to declare shell for every run.
