### ISSUE TITLE
Action: Update to the latest setup-node for GitHub actions, version 2

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#529]
The latest [setup-node](https://github.com/actions/setup-node#usage) is version 2 [for GitHub actions]

It makes sense that Dependabot does this by default, but if it doesn't it can be configured to do so as well (e.g., https://github.com/codeforamerica/brigade-project-index-statusboard/blob/a288e657777479ea82ce0fa09a056ef956a83ce3/.github/dependabot.yml#L3-L6)

_Originally posted by @k3KAW8Pnf7mkmdSMPHz27 in https://github.com/SuffolkLITLab/ALKiln/pull/527#discussion_r833621526_

**Comment by BryceStevenWilley** [comment]
The latest `setup-node` is now v3, and we are using it! In `action.yml` and in our own workflow! So this should be fixed, I'm gonna close it
