### ISSUE TITLE
Setup interview: Use action syntax to avoid testing tags

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#537]
GitHub tags act as if they're branches being pushed. They'll start tests. Docassemble doesn't know how to pull in that kind of thing, or maybe that branch gets immediately deleted or something (at least on AssemblyLine core) and so the tests fail. There's also no reason to test tags as their code is the same as the branch they're for.

Only some repos use tags, but I _think_ we can deal with it pretty easily with the right syntax. I got idea for the below from the conversation in https://github.community/t/using-on-push-tags-ignore-and-paths-ignore-together/16931/2:
```yml
push:
  branches:
    - "**"
  tags-ignore:
    - "**"
```

We'll have to test out that syntax somewhere with some github tag releases.

FYI, AssemblyLine's [method of doing this] is working, but it was funky for a while and I'm not convinced it won't become funky again. It's missing the `branches` part of the above code and that's what may have caused the problem.

**Comment by BryceStevenWilley** [comment]
Related to #757 and #760.

**Comment by plocket** [comment]
Was this closed by https://github.com/SuffolkLITLab/ALKiln/pull/823 with #760?
[Answer: I believe ALKiln actions aren't yet able to account for tags. Approaching it through ALKiln would be better, though.]
