### ISSUE TITLE
"I should see the phrase" is wrong when it contains an apostrophe 

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#542]
Trying to see if a phrase on screen is something like "You don't have access" won't work, since docassemble uses fancy apostrophes in the displayed html, which is technically a different character. Example below, lined up for convience
```
In Phrase:           "You don't have any service contacts you can add"
DA Page: '...Error\n\nYou don’t have any service contacts you can add.\n\nPress one of the ...' 
```
Since [the step](https://github.com/SuffolkLITLab/ALKiln/blob/4be7351bf979aad2bfffb33995808de1ac101551/lib/steps.js#L418-L421) code works with a node buffer, I'm not sure if you can do a text replace or something similar. At least for certain small things like that.

**Comment by plocket** [comment]
Just fyi, it is in [the documentation](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing/#observe-things-about-the-page) about this step. It might be good to add that possible outcome to the section about errors/warnings so people have a place to go to when they're experiencing what they find to be unexpected behavior.

It'd be great to handle it ourselves instead, but it could cause some combinatorial complexity.

**Comment by BryceStevenWilley** [comment]
I hadn't caught that in the docs! Agreed, some trouble shooting section in the docs would be nice. Making a unique warning might be useful too. It might be a lot more work, but would be interesting to make an [edit distance calculator](http://levenshtein.net/) ([python impl here](https://github.com/ztane/python-Levenshtein/tree/master/Levenshtein)), which could give you something like "Your phrase is very close (2 letters off) from this phrase in the text: ...".

Not sure what would be the combinatorial complexity here: we would just take the text from the screen, replace all of the fancy apostrophes from it and from the expected phrase, and then run the same `includes` function. Should just be linear in terms of the length of both stings, and shouldn't add any slow down at all.

**Comment by plocket** [comment]
I thought we were looking for the text in the usual way, which is very similar to how we look for selectors. We'd have had to try every combination. I just looked, though, and we're looking at the actual text, which will be a lot easier to manipulate. 👍 

If we're going to do that, we might want to also replace (off the top of my head):
- open and close single quotes
- open and close double quotes
- ellipses - I've seen people use them to quote text and in place of a more complicated js way to indicate that they can read more by clicking something.

I think there are more, but I can't remember them right now.

> ...an [edit distance calculator](http://levenshtein.net/) ([python impl here](https://github.com/ztane/python-Levenshtein/tree/master/Levenshtein)), which could give you something like "Your phrase is very close (2 letters off) from this phrase in the text: ...".

Sounds interesting and useful! We should add that as a separate issue, or a discussion item if we don't want it hanging around in issues. Not sure it'll be higher priority than, say, random input testing at the moment, though.

**Comment by plocket** [comment]
Note that we'll have to account for using apostrophes as well in case people copy the text from the page instead of typing it in. (Similarly with the others). It may be more useful to make a regex that allows alternates. [You can see the regex for our 'can't' and 'don't' in our Step sentence matchers.]
