### ISSUE TITLE
Remove tags from generated artifacts

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#563]
I.e. the changes in https://github.com/SuffolkLITLab/ALKiln/pull/561/files#diff-4b632aedc4c91285de358dd7cbcc91a52724745c5c759b81b3a6d80e8d6d7abcL187-R195.

Adding all of the tags to every output file makes the file names much too long, to the point where it's difficult to see more important information about an artifact. IMO tags are much less useful that the scenario id, which serves the same purpose.

**Comment by plocket** [comment]
Sounds good. I was on the fence about having them around anyway.

**Comment by plocket** [comment]
Closed by #568
