### ISSUE TITLE
Make things Windows compatible

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#594]
@trancode has been making great progress using `env-cmd` to make it such that we can run our npm commands that need env variables defined on Windows (ongoing work in https://github.com/SuffolkLITLab/ALKiln/tree/env-cmd).

The current roadblock is that some of the npm scripts do `run_cmd() { ... \"$@\" ... }; run_cmd`, which creates a shell / bash function, and then calls it. This fails in windows, since it doesn't know what to do with `run_cmd`.

Our best bet past this is to write the simple bash commands that we are using in a single JS file, making it automatically cross platfrom. The max things that we do in the bash commands are move around arguments and read in the status from other commands (https://nodejs.dev/en/learn/accept-input-from-the-command-line-in-nodejs might be useful).

**Comment by BryceStevenWilley** [comment]
Should be closed by https://github.com/SuffolkLITLab/ALKiln/pull/624, but I'm gonna double check and make sure it can work on windows.

**Comment by plocket** [comment]
I believe this worked on windows, but re-open if it didn't
