### ISSUE TITLE
Step: Allows dev to input letters so the robot will draw letters on the signature canvas

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#596]
Find a package that let the testing framework draw letters on a canvas. Our users, the developers writing the tests, would specify a name for the bot to draw on the canvas. Not at all urgent, but a nice addition for forms that can have multiple signatures.

First find the package, then we'll see how we can integrate it.

**Comment by plocket** [comment]
Could start by finding that package and getting it to work all on its own.

**Comment by jostran14** [comment]
https://www.npmjs.com/package/canvas/v/2.0.0-alpha.14#example

**Comment by jostran14** [comment]
[To make it easier for humans to draw on a canvas:]
https://www.npmjs.com/package/signature_pad
https://www.npmjs.com/package/canvas-free-drawing

**Comment by plocket** [comment]
lol, just found that canvas already comes with text drawing capability: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text. Thanks for sending us down that path, @trancode!

Now we just have to figure out how to integrate it!

**Comment by plocket** [comment]
This is the function to work on: https://github.com/SuffolkLITLab/ALKiln/blob/v4/lib/scope.js#L1922-L1936

**Comment by plocket** [comment]
Be sure to set your .env file `DEBUG=1`.

For now, if you don't want to learn how to write a docassemble interview, you can add a test to this feature file to run the test: https://github.com/SuffolkLITLab/ALKiln/blob/v4/docassemble/ALKilnTests/data/sources/interactive_steps.feature. You'll need to go up to https://github.com/SuffolkLITLab/ALKiln/blob/v4/docassemble/ALKilnTests/data/sources/interactive_steps.feature#L76 at the very least.

Run the `@i1` test first to make sure you practice running a test in debug mode so that you can see what happens on that signature screen. Then write your own test getting up to the signature screen and run that to make sure you're getting what you want. After _that_ you can start messing with the functionality.

You'll also want to make a version of the signing step that takes text as input: https://github.com/SuffolkLITLab/ALKiln/blob/v4/lib/steps.js#L978-L983

**Comment by plocket** [comment]
You can practice manipulating the canvas here: https://demo.docassemble.org/interview?i=docassemble.base%3Adata%2Fquestions%2Fexamples%2Fsignature.yml#page1

**Comment by jostran14** [comment]
-Added new feature test @i7 to test drawing name arg on canvas and tap continue
-Modified sign: method to pass in name argument to draw on canvas
-@i7 passed

**Comment by jostran14** [comment]
Next steps: ~Clean up code, npm run test,~ update to default branch, resolve conflicts, test again, and then make pull request.

**Comment by jostran14** [comment]
Pushed branch to pr with v4. Created new local branch to merge with v5. Need to resolve conflicts and test.

**Comment by jostran14** [comment]
Closed by #679
