### ISSUE TITLE
Test the JSON variable text value Step with multi-line text

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#597]
`(?:the )?text(?: in)?(?: the)?(?: JSON)?(?: var)?(?:iable)?(?: )?"([^"]+)" should be` (https://github.com/SuffolkLITLab/ALKiln/blob/releases/v4/lib/steps.js#L656)

We should test that the above Step can properly test a multi-line string. From testing in the wild, this does seem to work, so it's not urgent, but it would be good to have it under our belts.

**Comment by jostran14** [comment]
modify main interactive steps for test.

**Comment by jostran14** [comment]
none of the attempts passed. next time log the values in the json step that we are getting during the test.

**Comment by jostran14** [comment]
we might also test checking a value that has been set programmatically.

**Comment by jostran14** [comment]
item 1: alkiln currently can't write multiline text into a text area.
item 2: it probably can't correctly check json values for multiline strings created in text areas because they use `\r\n` for each new line.
item 3: you cannot accurately test for non-string json values for example numbers.
