### ISSUE TITLE
Make sure `SERVER_RELOAD_TIMEOUT_SECONDS` is being used as seconds and possibly alias

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#606]
~I think~ it's currently assumed to be MS despite the name.

Edit:
Also, the server setup timeout is called `MAX_SECONDS_FOR_SETUP`, so maybe this one should have an alias called something like `MAX_SECONDS_FOR_SERVER_RELOAD`.

**Comment by BryceStevenWilley** [comment]
Offending lines (where we get the value is seconds and set to the variables that is assumed to be in miliseconds): https://github.com/SuffolkLITLab/ALKiln/blob/f002a09a1f564c7fa39a97d4415ad6f5c2e3f643/lib/scope.js#L533-L534
