### ISSUE TITLE
Speed up the failure of tapable elements to appear on the page

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#613]
> The timeout is just in case none of [the tapable elements] are found. We don't want to wait for them for forever. 

That was my question, if none of them appear, we just wait for the timeout, which is a little silly IMO, especially for tests with longer timeouts.

This stackoverflow has some code that we should consider using: https://stackoverflow.com/questions/52497252/puppeteer-wait-until-page-is-completely-loaded.

_Originally posted by @BryceStevenWilley in https://github.com/SuffolkLITLab/ALKiln/pull/602#discussion_r959993336_

Reply:

> Always good to have a new eye on things! When I looked, I only remember finding stuff about `networidle` being unreliable. This looks like an interesting solution. We should back it up with the timeout as well, though, just in case it keeps changing for some reason. See [the comment below the answer](https://stackoverflow.com/questions/52497252/puppeteer-wait-until-page-is-completely-loaded#comment118988927_61304202) for an example.

**Comment by BryceStevenWilley** [comment]
A partial implementation of this is when searching for continue buttons, as in https://github.com/SuffolkLITLab/ALKiln/pull/620. We know when some of the continue buttons are present, they all should be. So if we iterate through them and don't see a continue button, we can stop immediately and say so.
