### ISSUE TITLE
Poor error message on page timeout

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#622]
I've gotten this error a few times:

> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "The target id was "ready to efile", but it took too long to try to reach it (over 1.6666666666666667 min). The test got stuck on "existing-service-contacts".".

When checking the error screenshots, it's clearly that a docassemble error screen showed up unexpectedly, but this error reads like something has gone wrong with ALKiln. I don't know enough about async funcs yet to try to fix it on my own.

**Comment by plocket** [comment]
I think this is an unhandled promise rejection error I believe. If so, there are ways to intercept that and we made an issue - #460.
