### ISSUE TITLE
Update `setup-node` action

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#625]
Got a notification on one of my runs that node12 is deprecated now: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. The version of `setup-node` that we use (version 1) [uses node12](https://github.com/actions/setup-node/blob/v1/action.yml#L20). Should be simple to see what the changes are between setup-node version 1 and version 3 (the current version) and update it. I know most of my testing has been with node 16 / 18, so I don't think the actual node version will change much.

https://github.com/actions/setup-node is the action repo.

**Comment by plocket** [comment]
Sounds like a good plan to me 👍 [Related to #615.]

**Comment by BryceStevenWilley** [comment]
Fixed in v5 with #664
