### ISSUE TITLE
DA doesn't allow slashes in branch names

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#634]
DA uses [`werkzeug.utils.secure_filename`](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/utils.py#L197-L241) to get git branches, which strips slashes from the name. This breaks our main way of specifying our default branch, `releases/v4`. :(  Github branches have [some rules](https://git-scm.com/docs/git-check-ref-format), but they are less strict than general werkzeug filenames.

Post #623, we are pulling branches kiln to run tests, so this issue breaks our tests, but only when running on the main branch.

As a temporary, fix, we've made a `v4` branch, and temporarily switched it to be the default branch. We'll work on trying to make a patch in DA, but while we do, we'll have to manually make sure the `releases/v4` is kept up to date with the `v4` branch (likely with a `reset --hard origin/v4` and a `--force push`).

**Comment by BryceStevenWilley** [comment]
Note that the tests are passing locally, in case that makes things a bit better. :)

**Comment by plocket** [comment]
I think we might be able to just merge `v4` into `releases/v4` here in github.

**Comment by plocket** [comment]
`v4` branch is made and is the default. For `releases/v4` I think we just need to update it on GitHub when we change the action.yml file. npm releases are independent of that stuff - they just depend on the version number published to npm. That means we can publish from branch `v4`. Release flow:
1. Publish to from `v4`
2. Merge the changes into `releases/v4` on GitHub

**Comment by plocket** [comment]
We'll use this issue to track the change to docassemble core now.

**Comment by BryceStevenWilley** [comment]
There is a PR out for upstream that should fix this: https://github.com/jhpyle/docassemble/pull/628

I did try it and we can't quite install the ALKiln package directly onto a server, as pip doesn't like when the name of a git repo is different from the name of the python package inside it; however 1) we shouldn't really need to install the tests on the server that often, and I believe installing from the playground package would work.

**Comment by plocket** [comment]
> I did try it and we can't quite install the ALKiln package directly onto a server

Will it still work for installing `v4` branch, or will we need to change our current workflow?

**Comment by BryceStevenWilley** [comment]
v4 is still fine. but we wouldn't need a long standing branch like that imo, as we don't usually install ALAutomatedTestingTests on the server that often, we just use it in the playground

**Comment by plocket** [comment]
I think it got merged! Huzzah!

**Comment by BryceStevenWilley** [comment]
Yep! There is still still one restriction on this package though; that we can't install it systemwide. This is because pip expects the repository name to be the same as the pythong package name, but it isn't, and for us it should't.  This is another issue with upstream docassemble, and is an issue I've run into before with [other packages](https://github.com/cloudconvert/cloudconvert-python).

That being said, nothing in our current process needs to have the AutomatedTestingTests installed or the server, so I'm okay with closing this issue.
