### ISSUE TITLE
Make node version official

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#645]
Pick an official recommended node version for the project. Add it to the internal documentation. Also put it somewhere machine-readable like in package.json and/or a .nvmrc file.

> With a node/npm toolchain you’ll have people coming at your project with a wild range of node/npm versions on their machine and people will either run into trouble getting set up or submit PRs that mess up your codebase if they’re not on the “blessed” version.

[Also include links to how to get different versions of node onto one's computer. nvm maybe.]

Also will need to take care of #625 and #615 as part of this.

**Comment by BryceStevenWilley** [comment]
Fixed in v5 with #664
