### ISSUE TITLE
`langs` command should run only langs

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#653]
Once https://github.com/SuffolkLITLab/ALKiln/pull/624 is merged, langs will still work, but it runs all of the tests, not just the translated ones. Slows down tests by most 2x, but likely less for more langs. Will have to add back some features to get it to work, but it shouldn't block https://github.com/SuffolkLITLab/ALKiln/pull/624 from being merged.

**Comment by plocket** [comment]
We've now decided that authors can use the `Examples` cucumber keyword and that all tests will be run every time. The latter is based on feedback from Quinten. From what I can tell, those are the only interviews with languages. If others start having issues, we'll address those then.
