### ISSUE TITLE
Consider: How to help people with phrase not found errors.

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#658]
Options:
- When phrase isn't found, put the actual text on the page into the report. That's pretty useful when cucumber does it in their error.
- Tell the dev to look at the screenshots. Maybe that'll be enough of a clue without flooding the report.
- > an [edit distance calculator](http://levenshtein.net/) ([python impl here](https://github.com/ztane/python-Levenshtein/tree/master/Levenshtein)), which could give you something like "Your phrase is very close (2 letters off) from this phrase in the text: ...". - #542

**Comment by BryceStevenWilley** [comment]
#542 has a more involved way of fixing this using edit distance, with IMO a bigger payoff. The closer to pointing folks to the exact spot their text differs the better.

**Comment by plocket** [comment]
In #542, we said to move that to its own issue. This could be the issue for that. Wish we could do a small diff on the text for the user, but not sure how we'd identify the right spot in the text. [Added this option to the top comment.]
