### ISSUE TITLE
Save copy of file the dev uploaded?

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#688]
For their later reference, so they don't have to go back and forth between their sources folder and the results.

**Comment by BryceStevenWilley** [comment]
FWIW, I think it's most clear to keep things we get from Kiln in the artifacts folder, and things we give Kiln in sources.

**Comment by plocket** [comment]
I'm not as sure, but I think we can at least retire this until/unless we hear that someone's finding it challenging to go back and forth between their own folder and the artifacts 👍
