### ISSUE TITLE
Discuss: For v5, start warning folks to use `ALKILN_` at the start of their env vars?

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#698]
To make sure devs don't override important env var values, like `PATH`, etc. [with their custom secret/sensitive env vars. E.g. vars like usernames and passwords, or whatever else they want to keep private or set in their environment.]

**Comment by BryceStevenWilley** [comment]
Quick summary of an conversation about this: 

We are already filtering out things like `PATH` in ALKilnInThePlayground. Those variables, if they cause issues, would already have been causing issues on github too.

Reasons to force `ALKILN_` at the beginning of vars:
1. we can't possibly know all of the env vars that are used in other programs or libraries, and there will be new ones added often.
2. debugging these issues could be rather confusing, and take a while to figure out the bug (though we haven't seen anything like this in the wild yet).

Reasons to not:
1. counter to 1) above: most libraries we use, like cucumber and puppeteer, do and will continue to prefix their env vars, like `CUCUMBER_`. So folks shouldn't run into issues there, and we can add those prefixes to the "dangerous_env_var_list" in ALKilnInThePlayground.
2. We'd make people invest of lot of effort now (and likely continued effort) to change and keep using ALKILN_ vars everywhere.
3.  we could warn folks to change their variables, without making forcing it or breaking people.

We generally landed not forcing this, implementing 3) in the meantime, and seeing what happens.
