### ISSUE TITLE
Update node packages

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#720]
We have 4 or 5 vulnerabilities. I know our repo isn't really impacted by the types of vulnerabilities that these packages introduce, but, y'know, good form.

**Comment by BryceStevenWilley** [comment]
I think this was fixed in https://github.com/SuffolkLITLab/ALKiln/pull/727 and https://github.com/SuffolkLITLab/ALKiln/pull/728, gonna close
