### ISSUE TITLE
Discuss: Should we check for a11y just before navigating instead of just after navigating

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#749]
If we check just before we leave a page, more fields may have been revealed during the course of answering questions. Of course, maybe some fields would have been hidden, but that's not as common.

**Comment by BryceStevenWilley** [comment]
IMO this isn't a big deal for a few reasons, strongest to weakest:
 * most users don't actually need to check accessibility of fields. They're the same for all of docassemble, and if there are accessiblity issues, authors can't fix them, they have to be fixed upstream. 
     * this tool's been useful for finding some of those issues, but what we need is just an interview with all fields types in it that fets continually checked in a different repo. I might set that up.
 * what you already said about the fact there's no actual gurantee that more fields will be shown. It's not strong enough an assumption to refactor the code IMO.
 * It matches what a user might experience more if we check on page landing (i.e. is this page I just landed on accessible) than at the end. I can't think of anything that would change the page to falsely pass more tests though.

Overall, I'm not sure a change in the timing like this would have much of a tangible benefit for most interviews.

**Comment by plocket** [comment]
Makes sense, I can go with that. I think that may just leave the question of when we should take the pic - just after the check or before navigation? I'd lean towards the former to avoid misleading output.

**Comment by BryceStevenWilley** [comment]
Agreed, just after the pic would be great. Probably not too hard, since we can take the screenshot (maybe manually?) right when we add the info to the report.

**Comment by plocket** [comment]
Added the note to #748.
