### ISSUE TITLE
Make ALKiln action work on GitHub tag releases

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#757]
Example of failing test: https://github.com/SuffolkLITLab/docassemble-ALAffidavitOfIndigency/actions/runs/6125747748/job/16628337375.

It looks like we manually [ignore tags and don't run workflows on tags](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/b23c5dc90f5280a8f518b604c37f7f4c70adc50f/.github/workflows/run_form_tests.yml#L8) in our other repos, but that bit isn't in [our suggested workflow example](https://github.com/SuffolkLITLab/ALKiln/blob/4625d58a58565c96edfe0fc6be8ad586a0156a2d/action.yml#L91).

This should be an easy fix though, and we could make it in a few places.

* in `action.yml`: if we used [`github.ref_name`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) instead of the current `github.ref`, we'd get 
    > The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, `feature-branch-1`.
    
    This is exactly what docassemble wants. Not sure why it does'n't work with the full version, but it doesn't. 
* a more hacky change with a smaller scope would be to include `refs/tags/` in https://github.com/SuffolkLITLab/ALKiln/blob/4625d58a58565c96edfe0fc6be8ad586a0156a2d/lib/utils/session_vars.js#L81
    I can confirm manually that telling docassemble the tag name works:
   
    ```
    ALKiln debug: Stored name of Project "ALKilnTestdocassembleALAffidavitOfIndigencyv2121694202276108" locally.
    ALKiln : Trying to pull code from the "v2.1.2" branch.
    ALKiln debug: Project name from file is "ALKilnTestdocassembleALAffidavitOfIndigencyv2121694202276108".
    ALKiln : Your Docassemble server finished pulling the package's code. 
    ALKiln setup: Success! Test setup has finished successfully.
    ```

**Comment by plocket** [comment]
Was this closed by https://github.com/SuffolkLITLab/ALKiln/pull/823 with #760?
