### ISSUE TITLE
Screenshot isn't informative anymore if the interview has the custom error page

### ISSUE THREAD

**Issue by nonprofittechy** [plocket/docassemble-cucumber#763]
![error_on-custom-error-action-User can upload exhibits-1695565690011](https://github.com/SuffolkLITLab/ALKiln/assets/7645641/4ab4b8af-153c-4d82-bb0f-82204569e7fc)

Perhaps there's a way to specially handle this page and get the hidden error message? maybe just to expand the accordion?

**Comment by BryceStevenWilley** [comment]
Had a conversation about this in Deep dive: our solution for Kiln is to get the DOM at the time when we take the screenshot; we can write this to an HTML artifact, and save it along with the screen shot.
