### ISSUE TITLE
PDF checking: copy all diffferent PDFS to a folder for easy replacement

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#776]
Consider adding a line to the log of "If this new PDF is what you want it to be, just replace it". In the future, consider a tool (or addition to Kiln itself) that copies the new PDFs into a separate artifact folder, for easy copy-replacing into the sources folder.

**Comment by plocket** [comment]
100% agree. Also, remember to add to the end of that sentence where to find the new file. i.e:

If this new PDF is what you want it to be, just replace it with the one that ALKiln just downloaded to "\<the path to the new file>"
