### ISSUE TITLE
dainstall doesn't install dependencies anymore

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#827]
docassemblecli changed dainstall a couple weeks ago and that's why our 3-parts dates tests are failing in the isolated GitHub server tests. The other AL tests are probably failing too. Maybe it's just getting buried in the noise.

Version 0.0.14 [changes when it restarts the server](https://github.com/jhpyle/docassemblecli/compare/v0.0.13...v0.0.14#diff-b29de36dc7d11398ab979dcf8683952f00ca0e53846c2e1545bff7fafc2cddd4). [I'm not sure what about it caused this issue, but changing my version of docassemblecli is what recreated the issue on my local server.] If there's no python file in the package being installed, it doesn't restart the server. It doesn't check for dependencies, so if there are dependencies, they don't get installed till the next restart/reload.

---

Old issue for posterity:

Topic: Running too fast?

[Sometimes our tests fail](https://github.com/SuffolkLITLab/ALKiln/actions/runs/7091525179) because the ThreePartsDate custom fields aren't done adding themselves to the page (I think): the error says that the element is not a `<select>` element and the pic shows a regular text input field. I checked manually on the testing and dev server, and the fields look fine. [This is happening in our GitHub server tests, which might be running a faster server than we're used to.]

I'm reluctant to slow the tests down more, especially since these lag issues are so unpredictable and we're already waiting the for a bit over the length of animation on at least `show if` fields. Maybe we can just slow down tests for custom datatypes? Maybe we just add more info to the ThreePartsDate error message, but I'm not sure how much that would help.

**Comment by plocket** [comment]
~Maybe we'll just slow down date steps... [at least for now]~ Didn't work because that wasn't the problem. Read above.

**Comment by BryceStevenWilley** [comment]
> Version 0.0.14 changes when it restarts the server. [I'm not sure what about it caused this issue, but changing my version of docassemblecli is what recreated the issue on my local server.] If there's no python file in the package being installed, it doesn't restart the server. It doesn't check for dependencies, so if there are dependencies, they don't get installed till the next restart/reload.

That's fairly frustrating. IMO, that's an upstream bug; we don't know which dependencies would get installed from `dainstall`, so it should usually restart, or at least should let the server tell us if we should restart. Happy to help raise this issue upstream or try to fix it. Until then, we should pin to version `0.0.13` to avoid that behavior.

**Comment by plocket** [comment]
Thank you. I'm debugging it and fixing it and should be able to make a PR soon. I like the idea of pinning the version in the future. For now, we do need other code in the new version, so we can't pin to `0.0.13` - it includes the code to ignore what's in the .gitignore. After this gets resolved, though, I'll look into pypi version-specific installation and we'll pin to the new working version 👍

**Comment by plocket** [comment]
Should be resolved by https://github.com/jhpyle/docassemblecli/pull/12 🤞

**Comment by plocket** [comment]
Should I make a `docassemblecli_alkiln` python package just for us? A bit more control maybe, but I'm reluctant to have another package to maintain.

**Comment by plocket** [comment]
It's been merged, though not yet released. [Apparently needs some fixes first, sorry about that.]
