### ISSUE TITLE
Takedown: Projects aren't being deleted anymore

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#835]
I could be wrong. I think I'm not seeing this on our own servers, but maybe I'm mistaken about which account the tests are running on. It might happen on failing tests. I'm not sure everyone can see these because they're not ours, but here's a failing test where deleting the project never runs:
https://github.com/LemmaLegalConsulting/docassemble-DangerLaw/actions/runs/7198403880/job/19607761373#step:3:1892

Here's a passing test where the Project does get deleted:
https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/actions/runs/7199780832/job/19612245162#step:3:462

Maybe something's wrong with our action.yml's `if` check for that Step. Gotta love GitHub actions.

**Comment by michaelhofrichter** [comment]
I'm seeing this when the tests fail. If I go into the Testing User's Playground, I'll see a collection of the projects where the test failed.

**Comment by plocket** [comment]
Closed by #843
